### ISSUE TITLE
No Gnome 47 support yet

### ISSUE THREAD

**Issue by erayrafet** [lennart-k/gnome-rounded-corners#35]
![image](https://github.com/user-attachments/assets/2b82e416-6d2e-4821-9d9c-7adb6e95beb0)

**Comment by Y2K350** [comment]
Wish gnome made it easier for extensions to be maintained. Every 6 months everything I use breaks and unfortunately I'm used to using like 30 extensions

**Comment by erayrafet** [comment]
I'm in the same boat, running Arch.

**Comment by lennart-k** [comment]
Thanks for the reminder. I currently don't have that much time to test it myself, but if you go into `~/.local/share/gnome-shell/extensions/Rounded_Corners@lennart-k/metadata.json` and add `47` under `shell-version` you can try out if it just works.
If you do that please tell me if it works so that I can publish a new version.

**Comment by erayrafet** [comment]
> Thanks for the reminder. I currently don't have that much time to test it myself, but if you go into `~/.local/share/gnome-shell/extensions/Rounded_Corners@lennart-k/metadata.json` and add `47` under `shell-version` you can try out if it just works. If you do that please tell me if it works so that I can publish a new version.

Indeed it works!
![image](https://github.com/user-attachments/assets/2f978dcd-a682-4e8f-b255-df729271164d)
![image](https://github.com/user-attachments/assets/cdf04977-e9f8-4afd-aadc-1349964f25c8)

**Comment by lennart-k** [comment]
Thanks a lot, the new version is now uploaded and in review. :)
